version: '2'
services:
  http-api:
    extends:
      file: docker-compose.base.yml
      service: http-api
    depends_on:
      - nats
      - app
    links:
      - nats:nats

  app:
    extends:
      file: docker-compose.base.yml
      service: app
    depends_on:
      - nats
      - postgres
    links:
      - nats:nats
      - postgres:postgres
    environment:
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_DB=$POSTGRES_DB

  nats:
    extends:
      file: docker-compose.base.yml
      service: nats

  postgres:
    extends:
      file: docker-compose.base.yml
      service: postgres
    environment:
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_USER=$POSTGRES_USER
