version: '2'
services:

  http-api:
    build: ./http-api
    ports:
      - "5000:5000"

  app:
    build: ./app
    environment:
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_DB=$POSTGRES_DB

  nats:
    image: nats:0.9.4

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_USER=$POSTGRES_USER
