version: '2'
services:

  http-api:
    build: ./http-api
    ports:
      - "5000:5000"
    volumes:
      - ./http-api/:/code
    depends_on:
      - nats
      - app
    links:
      - nats:nats

  app:
    build: ./app
    volumes:
      - ./app/:/code
    depends_on:
      - nats
      - postgres
    links:
      - nats:nats
      - postgres:postgres
    entrypoint: watchmedo auto-restart --recursive --pattern="*.py" --directory="." python app/main.py
    environment:
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_DB=$POSTGRES_DB

  nats:
    image: nats:0.9.4

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_USER=$POSTGRES_USER
